In [1]:
# !WANDB_PROJECT="cfe_finetuning" python3 -m wandb sweep sweep.yaml

In [2]:
import pandas as pd
import json

In [ ]:
import pandas as pd
import json
from pathlib import Path
import os

base_dir = Path("finetuning_eval")
json_files = list(base_dir.rglob("metrics.json"))
print(json_files)
all_dfs = []

for json_file in json_files:
    with open(json_file, "r") as f:
        data = json.load(f)

    scores_list = []
    for entry in data.get("all_primary_scores", []):
        alias, score = entry.rsplit(": ", 1)
        scores_list.append({"alias": alias, "primary_score": float(score)})
    df_primary_scores = pd.DataFrame(scores_list)

    tasks_list = []
    for task in data.get("tasks", []):
        entry = {"alias": task["alias"], "num_instances": task.get("num_instances"), "task_suite": json_file.parts[1]}
        entry.update(task.get("metrics", {}))
        tasks_list.append(entry)
    df_tasks = pd.DataFrame(tasks_list)

    df = pd.merge(df_primary_scores, df_tasks, on="alias", how="left")
    df["model"] = os.path.basename(json_file.parent)
    all_dfs.append(df)

df = pd.concat(all_dfs, ignore_index=True)

def rename(name):
    if "arc_easy" in name:
        return "ARC_E"
    elif "arc_challenge" in name:
        return "ARC_C"
    elif "boolq" in name:
        return "BoolQ"
    elif "csqa" in name:
        return "CSQA"
    elif "hellaswag" in name:
        return "HSwag"
    elif "mmlu_pro" in name:
        return "MMLU-Pro"
    elif "mmlu" in name:
        return "MMLU"
    elif "openbookqa" in name:
        return "OBQA"
    elif "piqa" in name:
        return "PIQA"
    elif "socialiqa" in name:
        return "SIQA"
    elif "winogrande" in name:
        return "WinoG"
    elif "agi" in name:
        return "AGIEval English"
    elif "bbh" in name:
        return "BBH"
    elif "gsm8k" in name:
        return "GSM8K"
    elif "triviaqa" in name:
        return "TriviaQA"
    else:
        return name+" TODO"
df["task"] = df["alias"].apply(rename)
df

[PosixPath('finetuning_eval/mmlu:mc::olmes/Qwen/Qwen2.5-0.5B-Instruct/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/allenai/OLMo-2-0425-1B-SFT/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/Qwen2.5-0.5B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/Qwen/Qwen2.5-0.5B-Instruct/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/allenai/OLMo-2-0425-1B-SFT/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/Qwen2.5-0.5B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/olmo_2_heldout::olmes/allenai/OLMo-2-0425-1B-SFT/metrics.json'), PosixPath('finetuning_eval/olmo_2_heldout::olmes/Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/olmo_2_heldout::olmes/OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json')]

,alias,primary_score_x,num_instances,task_suite,bits_per_byte_corr_micro,bits_per_byte_corr_macro,acc_per_byte_micro,acc_per_byte_macro,logits_per_char_corr_micro,logits_per_char_corr_macro,...,acc_uncond,exact_match_micro,exact_match_macro,exact_match_simple_micro,exact_match_simple_macro,exact_match_simple,exact_match,f1,recall,task
0,mmlu:mc::olmes,0.475960,14042,mmlu:mc::olmes,0.96504,0.9343,0.463324,0.47596,-0.668915,-0.647608,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
1,mmlu_abstract_algebra:mc::olmes,0.360000,100,mmlu:mc::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
2,mmlu_anatomy:mc::olmes,0.422222,135,mmlu:mc::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
3,mmlu_astronomy:mc::olmes,0.453947,152,mmlu:mc::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
4,mmlu_business_ethics:mc::olmes,0.520000,100,mmlu:mc::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592,mmlu_pro_other:mc::none,0.160173,924,olmo_2_heldout::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
593,mmlu_pro_history:mc::none,0.160105,381,olmo_2_heldout::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
594,mmlu_pro_psychology:mc::none,0.180451,798,olmo_2_heldout::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
595,mmlu_pro_law:mc::none,0.126249,1101,olmo_2_heldout::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mmlu
596,triviaqa::olmes,0.561167,7993,olmo_2_heldout::olmes,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.515451,0.561167,0.5426,triviaqa

In [4]:
df_f = df[["task_suite", "alias", "primary_score_y", "model", "task"]].copy()
df_f = df_f.groupby(["model", "task"])["primary_score_y"].mean().reset_index()
df_f = df_f.pivot(index="model", columns="task", values="primary_score_y")
df_f.insert(0, "avg", df_f.mean(axis=1, numeric_only=True) 
)
external_models = ["Qwen2.5-0.5B-Instruct", "OLMo-2-0425-1B-SFT", "Llama-3.2-1B-Instruct"]
df_f = df_f.reset_index()
df_f["type"] = df_f["model"].apply(lambda x: "external" if x in external_models else "own")
#
def latex_escape(s):
    replacements = {
        "&": "\\&",
        "%": "\\%",
        "$": "\\$",
        "#": "\\#",
        "_": "\\_",
        "{": "\\{",
        "}": "\\}",
        "~": "\\textasciitilde{}",
        "^": "\\textasciicircum{}",
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s





for name, group in df_f.groupby("type"):
    display(group)
    group = group.drop(columns="type").set_index("model")
    for col in group.columns:
        max_val = df_f[col].max()
        group[col] = group[col].apply(lambda x: f"\\textbf{{{x:.2f}}}" if x == max_val else f"{x:.2f}")


    group.columns = [latex_escape(str(c)) for c in group.columns]
    group.columns = [f"\\rotatebox{{45}}{{{latex_escape(str(c))}}}" for c in group.columns]

    group.index = [i.split("_")[0] for i in group.index]
    group.index.name = "LoRA fine-tuned models" if name == "own" else "External models"
    print(group.index)

    file_path = f"tables/olmes-{name}.tex"
    os.makedirs("tables", exist_ok=True)
    with open(file_path, "w") as f:
        f.write(group.to_latex(
            index=True,
            header=name == "own",
            escape=False
        ))

task,model,avg,agi,arc,bbh,boolq,core,csqa,gsm8k,hellaswag,mmlu,openbookqa,piqa,socialiqa,triviaqa,winogrande,type
1,OLMo-2-0425-1B-SFT,0.546546,0.362203,0.614399,0.315006,0.749333,0.649204,0.645919,0.427597,0.612333,0.381237,0.510667,0.724,0.581000,0.481006,0.597737,external
3,Qwen2.5-0.5B-Instruct,0.572635,NaN,0.603680,NaN,0.679000,0.587870,0.599509,NaN,0.487000,0.475960,0.535333,0.667,0.561667,NaN,0.529334,external

Index(['OLMo-2-0425-1B-SFT', 'Qwen2.5-0.5B-Instruct'], dtype='object', name='External models')

task,model,avg,agi,arc,bbh,boolq,core,csqa,gsm8k,hellaswag,mmlu,openbookqa,piqa,socialiqa,triviaqa,winogrande,type
0,Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr...,0.440570,0.236339,0.493131,0.299411,0.634000,0.589646,0.479934,0.074299,0.522667,0.267748,0.392000,0.673000,0.478000,0.442699,0.585109,own
2,OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_...,0.529634,0.336502,0.617850,0.302094,0.680333,0.641340,0.570844,0.357847,0.598667,0.374130,0.498667,0.708667,0.551667,0.561167,0.615101,own
4,Qwen2.5-0.5B_tulu-3-sft-olmo-2-mixture-0225_lr...,0.565407,NaN,0.601798,NaN,0.656667,0.582547,0.570571,NaN,0.487667,0.483666,0.521333,0.665667,0.556667,NaN,0.527493,own

Index(['Llama-3.2-1B', 'OLMo-2-0425-1B', 'Qwen2.5-0.5B'], dtype='object', name='LoRA fine-tuned models')

In [5]:
# pip install pygsheets

In [6]:
# pip install lm_eval

In [7]:
!nvidia-smi

No devices were found

In [8]:
# !python3 ./merge_lora_to_hf.py \
#   --base_model EleutherAI/pythia-31m \
#   --adapter_dir /srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train \
#   --output_dir /srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train-merged

In [9]:
import multiprocessing as mp
mp.set_start_method('spawn', force=True)

In [10]:
!

In [11]:
# import subprocess
# import os

# # Change working directory to olmes
# olmes_dir = os.path.join("olmes")
# os.chdir(olmes_dir)

# cmd = [
#     "CUDA_VISIBLE_DEVICES=0 python3", "-m", "oe_eval.launch",
#     "--model","/srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train-merged",
#     "--task", "tulu_3_dev",
#     "--output-dir", "./finetuning_eval/"
  
# ]

# subprocess.run(cmd, check=True)