In [ ]:
# !WANDB_PROJECT="cfe_finetuning" python3 -m wandb sweep sweep.yaml

In [4]:
import pandas as pd
import json

In [22]:
import pandas as pd
import json

with open("finetuning_eval/pythia-31m_tulu-v2-sft-mixture_train-merged/metrics.json", "r") as f:
    data = json.load(f)


scores_list = []
for entry in data.get("all_primary_scores", []):
    alias, score = entry.rsplit(": ", 1)
    scores_list.append({"alias": alias, "primary_score": float(score)})
df_primary_scores = pd.DataFrame(scores_list)


tasks_list = []
for task in data.get("tasks", []):

    entry = {"alias": task["alias"], "num_instances": task.get("num_instances")}
    entry.update(task.get("metrics", {}))
    tasks_list.append(entry)
df_tasks = pd.DataFrame(tasks_list)

df = pd.merge(df_primary_scores, df_tasks, on="alias", how="left")
df

,alias,primary_score_x,num_instances,primary_score_micro,primary_score_macro,logits_per_char_corr_micro,logits_per_char_corr_macro,sum_logits_corr_micro,sum_logits_corr_macro,bits_per_byte_corr_micro,...,acc_per_char,acc_per_byte,sum_logits_corr,logits_per_token_corr,logits_per_char_corr,bits_per_byte_corr,exact_match_simple,exact_match,f1,recall
0,agi_eval_english:1shot::olmes,0.232114,2646,0.223356,0.232114,-1.908329,-1.898482,-3.816658,-3.796964,2.753137,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bbh:cot-v1::olmes,0.110134,6511,0.104131,0.110134,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mmlu_pro:mc::none,0.112866,12032,0.112866,0.113261,-2.068762,-2.023758,-4.137524,-4.047515,2.984593,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,agi_eval_lsat-ar:1shot::olmes,0.208696,230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.208696,0.208696,-3.515195,-3.515195,-1.757597,2.535677,NaN,NaN,NaN,NaN
4,agi_eval_lsat-lr:1shot::olmes,0.200000,510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.200000,0.200000,-3.470496,-3.470496,-1.735248,2.503434,NaN,NaN,NaN,NaN
5,agi_eval_lsat-rc:1shot::olmes,0.189591,269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.189591,0.189591,-3.213456,-3.213456,-1.606728,2.318018,NaN,NaN,NaN,NaN
6,agi_eval_logiqa-en:1shot::olmes,0.202765,651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.202765,0.202765,-4.147406,-4.147406,-2.073703,2.991721,NaN,NaN,NaN,NaN
7,agi_eval_sat-math:1shot::olmes,0.240909,220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.240909,0.240909,-4.780677,-4.780677,-2.390338,3.448529,NaN,NaN,NaN,NaN
8,agi_eval_sat-en:1shot::olmes,0.310680,206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.310680,0.310680,-3.832254,-3.832254,-1.916127,2.764387,NaN,NaN,NaN,NaN
9,agi_eval_aqua-rat:1shot::olmes,0.255906,254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.255906,0.255906,-2.971387,-2.971387,-1.485694,2.143403,NaN,NaN,NaN,NaN
10,agi_eval_gaokao-english:1shot::olmes,0.248366,306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.248366,0.248366,-4.444843,-4.444843,-2.222422,3.206277,NaN,NaN,NaN,NaN
11,bbh_boolean_expressions:cot-v1::olmes,0.000000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
12,bbh_causal_judgement:cot-v1::olmes,0.459893,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.443850,0.459893,NaN,NaN
13,bbh_date_understanding:cot-v1::olmes,0.096000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.096000,0.096000,NaN,NaN
14,bbh_disambiguation_qa:cot-v1::olmes,0.296000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.296000,0.296000,NaN,NaN
15,bbh_dyck_languages:cot-v1::olmes,0.016000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.016000,0.016000,NaN,NaN
16,bbh_formal_fallacies:cot-v1::olmes,0.088000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.088000,0.088000,NaN,NaN
17,bbh_geometric_shapes:cot-v1::olmes,0.032000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.032000,0.032000,NaN,NaN
18,bbh_hyperbaton:cot-v1::olmes,0.120000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.120000,0.120000,NaN,NaN
19,bbh_logical_deduction_five_objects:cot-v1::olmes,0.020000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.020000,0.020000,NaN,NaN
20,bbh_logical_deduction_seven_objects:cot-v1::olmes,0.024000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.024000,0.024000,NaN,NaN
21,bbh_logical_deduction_three_objects:cot-v1::olmes,0.032000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.032000,0.032000,NaN,NaN
22,bbh_movie_recommendation:cot-v1::olmes,0.248000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.236000,0.248000,NaN,NaN
23,bbh_multistep_arithmetic_two:cot-v1::olmes,0.000000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
24,bbh_navigate:cot-v1::olmes,0.488000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.488000,0.488000,NaN,NaN
25,bbh_object_counting:cot-v1::olmes,0.000000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
26,bbh_penguins_in_a_table:cot-v1::olmes,0.198630,146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.198630,0.198630,NaN,NaN
27,bbh_reasoning_about_colored_objects:cot-v1::olmes,0.052000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.040000,0.052000,NaN,NaN
28,bbh_ruin_names:cot-v1::olmes,0.208000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.208000,0.208000,NaN,NaN
29,bbh_salient_translation_error_detection:cot-v1...,0.152000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.152000,0.152000,NaN,NaN
30,bbh_snarks:cot-v1::olmes,0.219101,178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.219101,0.219101,NaN,NaN
31,bbh_sports_understanding:cot-v1::olmes,0.056000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.028000,0.056000,NaN,NaN
32,bbh_temporal_sequences:cot-v1::olmes,0.000000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
33,bbh_tracking_shuffled_objects_five_objects:cot...,0.060000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.060000,0.060000,NaN,NaN
34,bbh_tracking_shuffled_objects_seven_objects:co...,0.036000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.036000,0.036000,NaN,NaN
35,bbh_tracking_shuffled_objects_three_objects:co...,0.040000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.040000,0.040000,NaN,NaN
36,bbh_web_of_lies:cot-v1::olmes,0.032000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.008000,0.032000,NaN,NaN
37,bbh_word_sorting:cot-v1::olmes,0.000000,250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN
38,gsm8k::olmes,0.005307,1319,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.005307,NaN,NaN
39,mmlu_pro_math:mc::none,0.097705,1351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.097705,0.097705,-4.839105,-4.839105,-2.419552,3.490676,NaN,NaN,NaN,NaN
40,mmlu_pro_health:mc::none,0.117359,818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.117359,0.117359,-3.656379,-3.656379,-1.828190,2.637520,NaN,NaN,NaN,NaN
41,mmlu_pro_physics:mc::none,0.117783,1299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.117783,0.117783,-4.896087,-4.896087,-2.448043,3.531780,NaN,NaN,NaN,NaN
42,mmlu_pro_business:mc::none,0.108999,789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.108999,0.108999,-3.919757,-3.919757,-1.959879,2.827507,NaN,NaN,NaN,NaN
43,mmlu_pro_biology:mc::none,0.105997,717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.105997,0.105997,-3.350799,-3.350799,-1.675399,2.417090,NaN,NaN,NaN,NaN
44,mmlu_pro_chemistry:mc::none,0.116608,1132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.116608,0.116608,-3.928836,-3.928836,-1.964418,2.834056,NaN,NaN,NaN,NaN
45,mmlu_pro_computer science:mc::none,0.114634,410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.114634,0.114634,-3.837624,-3.837624,-1.918812,2.768261,NaN,NaN,NaN,NaN
46,mmlu_pro_economics:mc::none,0.138626,844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.138626,0.138626,-4.282719,-4.282719,-2.141359,3.089329,NaN,NaN,NaN,NaN
47,mmlu_pro_engineering:mc::none,0.105263,969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.105263,0.105263,-4.301114,-4.301114,-2.150557,3.102598,NaN,NaN,NaN,NaN
48,mmlu_pro_philosophy:mc::none,0.112224,499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.112224,0.112224,-3.779429,-3.779429,-1.889715,2.726282,NaN,NaN,NaN,NaN
49,mmlu_pro_other:mc::none,0.103896,924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.103896,0.103896,-4.062392,-4.062392,-2.031196,2.930396,NaN,NaN,NaN,NaN
50,mmlu_pro_history:mc::none,0.115486,381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.115486,0.115486,-3.886253,-3.886253,-1.943127,2.803339,NaN,NaN,NaN,NaN
51,mmlu_pro_psychology:mc::none,0.110276,798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.110276,0.110276,-4.124455,-4.124455,-2.062227,2.975165,NaN,NaN,NaN,NaN
52,mmlu_pro_law:mc::none,0.120799,1101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.120799,0.120799,-3.800261,-3.800261,-1.900131,2.741309,NaN,NaN,NaN,NaN
53,triviaqa::olmes,0.034136,7993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000125,0.034136,0.003128

In [24]:
df["benchmark"] = df["alias"].apply(lambda x: x.split("_")[0])

In [29]:
df.groupby("benchmark")[["primary_score_x", ]].mean()

                   primary_score_x
benchmark
agi                       0.232114
bbh                       0.110134
bbh:cot-v1::olmes         0.110134
gsm8k::olmes              0.005307
mmlu                      0.113235
triviaqa::olmes           0.034136

In [2]:
# pip install pygsheets

In [3]:
# pip install lm_eval

In [4]:
!nvidia-smi

Tue Sep  9 15:07:39 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-16GB           On  |   00000000:85:00.0 Off |                    0 |
| N/A   31C    P0             42W /  300W |       1MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla V100-SXM2-16GB           On  |   00000000:86:00.0 Off |                    0 |
| N/A   33C    P0             42W /  300W |       1MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [5]:
# !python3 ./merge_lora_to_hf.py \
#   --base_model EleutherAI/pythia-31m \
#   --adapter_dir /srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train \
#   --output_dir /srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train-merged

In [3]:
import multiprocessing as mp
mp.set_start_method('spawn', force=True)

In [ ]:
!

2025-09-09 15:11:15,499 [WARNING] No config found for model:/srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train-merged, using raw model
2025-09-09 15:11:15,501 [INFO] Running eval locally on 99 tasks!

In [7]:
# import subprocess
# import os

# # Change working directory to olmes
# olmes_dir = os.path.join("olmes")
# os.chdir(olmes_dir)

# cmd = [
#     "CUDA_VISIBLE_DEVICES=0 python3", "-m", "oe_eval.launch",
#     "--model","/srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train-merged",
#     "--task", "tulu_3_dev",
#     "--output-dir", "./finetuning_eval/"
  
# ]

# subprocess.run(cmd, check=True)