In [1]:
# !WANDB_PROJECT="cfe_finetuning" python3 -m wandb sweep sweep.yaml

In [2]:
import pandas as pd
import json

In [3]:
import pandas as pd
import json
from pathlib import Path
import os

base_dir = Path("finetuning_eval")
json_files = list(base_dir.rglob("metrics.json"))
print(json_files)
all_dfs = []

for json_file in json_files:
    with open(json_file, "r") as f:
        data = json.load(f)

    scores_list = []
    for entry in data.get("all_primary_scores", []):
        alias, score = entry.rsplit(": ", 1)
        scores_list.append({"alias": alias, "primary_score": float(score)})
    df_primary_scores = pd.DataFrame(scores_list)

    tasks_list = []
    for task in data.get("tasks", []):
        entry = {"alias": task["alias"], "num_instances": task.get("num_instances"), "task_suite": json_file.parts[1]}
        entry.update(task.get("metrics", {}))
        tasks_list.append(entry)
    df_tasks = pd.DataFrame(tasks_list)

    df = pd.merge(df_primary_scores, df_tasks, on="alias", how="left")
    df["model"] = os.path.basename(json_file.parent)
    all_dfs.append(df)

df = pd.concat(all_dfs, ignore_index=True)

def rename(name):
    if "arc_easy" in name:
        return "ARC\_E"
    elif "arc_challenge" in name:
        return "ARC\_C"
    elif "boolq" in name:
        return "BoolQ"
    elif "csqa" in name:
        return "CSQA"
    elif "hellaswag" in name:
        return "HSwag"
    elif "mmlu_pro" in name:
        return "MMLU-Pro"
    elif "mmlu" in name:
        return "MMLU"
    elif "openbookqa" in name:
        return "OBQA"
    elif "piqa" in name:
        return "PIQA"
    elif "socialiqa" in name:
        return "SIQA"
    elif "winogrande" in name:
        return "WinoG"
    elif "agi" in name:
        return "AGIEval"
    elif "bbh" in name:
        return "BBH"
    elif "gsm8k" in name:
        return "GSM8K"
    elif "triviaqa" in name:
        return "TriviaQA"
    elif "coqa" in name:
        return "CoQA"
    elif "drop" in name:
        return "DROP"
    elif "jeopardy" in name:
        return "JPRDY"
    elif "naturalqs" in name:
        return "NatQs"
    elif "squad" in name:
        return "SQuAD"
    else:
        return name+" TODO"
df["task"] = df["alias"].apply(rename)
df = df[~df['task'].str.contains("TODO", na=False)]
cols = df.columns[:2].tolist() + sorted(df.columns[2:])
df = df[cols]
df

[PosixPath('finetuning_eval/mmlu:mc::olmes/Qwen/Qwen2.5-0.5B-Instruct/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/meta-llama/Llama-3.2-1B-Instruct/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/allenai/OLMo-2-0425-1B-SFT/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/Qwen2.5-0.5B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/mmlu:mc::olmes/OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/olmo_2_generative::olmes/Qwen/Qwen2.5-0.5B-Instruct/metrics.json'), PosixPath('finetuning_eval/olmo_2_generative::olmes/meta-llama/Llama-3.2-1B-Instruct/metrics.json'), PosixPath('finetuning_eval/olmo_2_generative::olmes/allenai/OLMo-2-0425-1B-SFT/metrics.json'), PosixPath('finetuning_eval/olmo_2_generative::olmes/Qwen2.5-0.5B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/olmo_2_generative::olmes/Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/olmo_2_generative::olmes/OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/Qwen/Qwen2.5-0.5B-Instruct/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/meta-llama/Llama-3.2-1B-Instruct/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/allenai/OLMo-2-0425-1B-SFT/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/Qwen2.5-0.5B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/core_9mcqa::olmes/OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/olmo_2_heldout::olmes/allenai/OLMo-2-0425-1B-SFT/metrics.json'), PosixPath('finetuning_eval/olmo_2_heldout::olmes/Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json'), PosixPath('finetuning_eval/olmo_2_heldout::olmes/OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_lr1e-05_seed42-merged/metrics.json')]

,alias,primary_score_x,acc_per_byte,acc_per_byte_macro,acc_per_byte_micro,acc_per_char,acc_per_char_macro,acc_per_char_micro,acc_per_token,acc_per_token_macro,...,num_instances,primary_score_macro,primary_score_micro,primary_score_y,recall,sum_logits_corr,sum_logits_corr_macro,sum_logits_corr_micro,task,task_suite
0,mmlu:mc::olmes,0.475960,NaN,0.47596,0.463324,NaN,0.47596,0.463324,NaN,0.47596,...,14042,0.47596,0.463324,0.475960,NaN,NaN,-1.295215,-1.33783,MMLU,mmlu:mc::olmes
1,mmlu_abstract_algebra:mc::olmes,0.360000,0.360000,NaN,NaN,0.360000,NaN,NaN,0.360000,NaN,...,100,NaN,NaN,0.360000,NaN,-1.454086,NaN,NaN,MMLU,mmlu:mc::olmes
2,mmlu_anatomy:mc::olmes,0.422222,0.422222,NaN,NaN,0.422222,NaN,NaN,0.422222,NaN,...,135,NaN,NaN,0.422222,NaN,-1.301614,NaN,NaN,MMLU,mmlu:mc::olmes
3,mmlu_astronomy:mc::olmes,0.453947,0.453947,NaN,NaN,0.453947,NaN,NaN,0.453947,NaN,...,152,NaN,NaN,0.453947,NaN,-1.274745,NaN,NaN,MMLU,mmlu:mc::olmes
4,mmlu_business_ethics:mc::olmes,0.520000,0.520000,NaN,NaN,0.520000,NaN,NaN,0.520000,NaN,...,100,NaN,NaN,0.520000,NaN,-1.119682,NaN,NaN,MMLU,mmlu:mc::olmes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709,mmlu_pro_other:mc::none,0.160173,0.160173,NaN,NaN,0.160173,NaN,NaN,0.160173,NaN,...,924,NaN,NaN,0.160173,NaN,-2.376427,NaN,NaN,MMLU-Pro,olmo_2_heldout::olmes
710,mmlu_pro_history:mc::none,0.160105,0.160105,NaN,NaN,0.160105,NaN,NaN,0.160105,NaN,...,381,NaN,NaN,0.160105,NaN,-2.282512,NaN,NaN,MMLU-Pro,olmo_2_heldout::olmes
711,mmlu_pro_psychology:mc::none,0.180451,0.180451,NaN,NaN,0.180451,NaN,NaN,0.180451,NaN,...,798,NaN,NaN,0.180451,NaN,-2.428124,NaN,NaN,MMLU-Pro,olmo_2_heldout::olmes
712,mmlu_pro_law:mc::none,0.126249,0.126249,NaN,NaN,0.126249,NaN,NaN,0.126249,NaN,...,1101,NaN,NaN,0.126249,NaN,-2.354966,NaN,NaN,MMLU-Pro,olmo_2_heldout::olmes
713,triviaqa::olmes,0.561167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7993,NaN,NaN,0.561167,0.5426,NaN,NaN,NaN,TriviaQA,olmo_2_heldout::olmes

In [4]:
df_f = df[["task_suite", "alias", "primary_score_y", "model", "task"]].copy()
df_f = df_f.groupby(["model", "task"])["primary_score_y"].mean().reset_index()
df_f = df_f.pivot(index="model", columns="task", values="primary_score_y")
df_f.insert(0, "avg", df_f.mean(axis=1, numeric_only=True) 
)
external_models = ["Qwen2.5-0.5B-Instruct", "OLMo-2-0425-1B-SFT", "Llama-3.2-1B-Instruct"]
df_f = df_f.reset_index()
df_f["type"] = df_f["model"].apply(lambda x: "external" if x in external_models else "own")
#





for name, group in df_f.groupby("type"):
    display(group)
    group = group.drop(columns="type").set_index("model")
    for col in group.columns:
        max_val = df_f[col].max()
        def fmt(x):
            formatted = f"{x:.2f}".lstrip("0") if x < 1 else f"{x:.2f}"
            if x == max_val:
                return f"\\textbf{{{formatted}}}"
            return formatted
        
        group[col] = group[col].apply(fmt)


    group.columns = [str(c) for c in group.columns]
    group.columns = [f"\\rotatebox{{45}}{{{str(c)}}}" for c in group.columns]

    group.index = [i.split("_")[0] for i in group.index]
    group.index.name = "LoRA models" if name == "own" else "External models"
    print(group.index)

    file_path = f"tables/olmes-{name}.tex"
    os.makedirs("tables", exist_ok=True)
    with open(file_path, "w") as f:
        f.write(group.to_latex(
            index=True,
            header=name == "own",
            escape=False
        ))

task,model,avg,AGIEval,ARC\_C,ARC\_E,BBH,BoolQ,CSQA,CoQA,DROP,...,MMLU,MMLU-Pro,NatQs,OBQA,PIQA,SIQA,SQuAD,TriviaQA,WinoG,type
0,Llama-3.2-1B-Instruct,0.547756,NaN,0.489761,0.731333,NaN,0.636000,0.630358,0.669044,0.28838,...,0.464886,0.417454,0.19971,0.538000,0.707333,0.566000,0.789595,NaN,0.587214,external
2,OLMo-2-0425-1B-SFT,0.525708,0.362203,0.481797,0.747000,0.315006,0.749333,0.645919,0.715931,0.33337,...,0.440424,0.213020,0.17196,0.510667,0.724000,0.581000,0.831776,0.481006,0.597737,external
4,Qwen2.5-0.5B-Instruct,0.497493,NaN,0.494027,0.713333,NaN,0.679000,0.599509,0.412742,0.24967,...,0.482305,0.390304,0.08591,0.535333,0.667000,0.561667,0.740223,NaN,0.529334,external

Index(['Llama-3.2-1B-Instruct', 'OLMo-2-0425-1B-SFT', 'Qwen2.5-0.5B-Instruct'], dtype='object', name='External models')

task,model,avg,AGIEval,ARC\_C,ARC\_E,BBH,BoolQ,CSQA,CoQA,DROP,...,MMLU,MMLU-Pro,NatQs,OBQA,PIQA,SIQA,SQuAD,TriviaQA,WinoG,type
1,Llama-3.2-1B_tulu-3-sft-olmo-2-mixture-0225_lr...,0.422800,0.236339,0.380262,0.606000,0.299411,0.634000,0.479934,0.635770,0.25754,...,0.306858,0.156592,0.12164,0.392000,0.673000,0.478000,0.678449,0.442699,0.585109,own
3,OLMo-2-0425-1B_tulu-3-sft-olmo-2-mixture-0225_...,0.514223,0.336502,0.482366,0.753333,0.302094,0.680333,0.570844,0.681911,0.33318,...,0.438869,0.190136,0.19201,0.498667,0.708667,0.551667,0.803458,0.561167,0.615101,own
5,Qwen2.5-0.5B_tulu-3-sft-olmo-2-mixture-0225_lr...,0.502875,NaN,0.494596,0.709000,NaN,0.656667,0.570571,0.586430,0.22469,...,0.490577,0.390360,0.10876,0.521333,0.665667,0.556667,0.718284,NaN,0.527493,own

Index(['Llama-3.2-1B', 'OLMo-2-0425-1B', 'Qwen2.5-0.5B'], dtype='object', name='LoRA models')

In [5]:
# pip install pygsheets

In [6]:
# pip install lm_eval

In [7]:
!nvidia-smi

No devices were found

In [8]:
# !python3 ./merge_lora_to_hf.py \
#   --base_model EleutherAI/pythia-31m \
#   --adapter_dir /srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train \
#   --output_dir /srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train-merged

In [9]:
import multiprocessing as mp
mp.set_start_method('spawn', force=True)

In [10]:
!

In [11]:
# import subprocess
# import os

# # Change working directory to olmes
# olmes_dir = os.path.join("olmes")
# os.chdir(olmes_dir)

# cmd = [
#     "CUDA_VISIBLE_DEVICES=0 python3", "-m", "oe_eval.launch",
#     "--model","/srv/home/users/loriss21cs/cfe/models/pythia-31m_tulu-v2-sft-mixture_train-merged",
#     "--task", "tulu_3_dev",
#     "--output-dir", "./finetuning_eval/"
  
# ]

# subprocess.run(cmd, check=True)