In [1]:
import os
from multiprocess import set_start_method
set_start_method("spawn")
import logging
logger = logging.getLogger("ignite.handlers.early_stopping.EarlyStopping")
logger.setLevel(logging.WARNING)

In [2]:
# import wandb 
from coreset_trainer.custom_olmo import DecomposedOlmo2
# from coreset_trainer.custom_phi import DecomposedPhiCausalLM

from transformers import Trainer, AutoModelForCausalLM, AutoTokenizer, TrainingArguments, DataCollatorForLanguageModeling
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType, PeftModel

from coreset_trainer.trainer import CoresetTrainer
import os
import torch

import argparse

from coreset_trainer.train import tokenize_dataset

In [3]:
from influence_estimation.data_inf import DataInfEstimator
from influence_estimation.less_inf import LESSEstimator
from datasets import load_dataset


# base_model_path = "distilbert/distilgpt2"
# base_model_path = "allenai/OLMo-2-0425-1B"
# base_model_path = "allenai/OLMo-2-0425-1B"
# adapter_path = "/srv/home/users/loriss21cs/cfe/models/distilgpt2_tulu-v2-sft-mixture"
# adapter_path = "/srv/home/users/loriss21cs/cfe/models/OLMo-2-0425-1B_tulu-v2-sft-mixture"

train_dataset = load_dataset("allenai/tulu-v2-sft-mixture", split="train").shuffle(seed=42).select(range(1000))
train_dataset = train_dataset.map(
    lambda example, idx: {"indices": idx},
    with_indices=True
)





test_dataset = load_dataset("allenai/tulu-v2-sft-mixture", split="train").shuffle(seed=0).select(range(1000))
test_dataset = test_dataset.map(
    lambda example, idx: {"indices": idx},
    with_indices=True
)

In [4]:
estimators = [
    # LESSEstimator(base_model_path, adapter_path, train_dataset, test_dataset,fast_implementation=False),
    # LESSEstimator(base_model_path, adapter_path, train_dataset, test_dataset,fast_implementation=True),
    LESSEstimator("./models/pythia-31m_tulu-v2-sft-mixture_train", train_dataset, test_dataset),
    LESSEstimator("./models/pythia-31m_tulu-v2-sft-mixture_train", train_dataset, test_dataset, normalize=False),
    DataInfEstimator("./models/pythia-31m_tulu-v2-sft-mixture_train",train_dataset, test_dataset)
   
]

In [40]:
import pandas as pd
from scipy.stats import spearmanr

def rowwise_rank_corr(df1: pd.DataFrame, df2: pd.DataFrame):    
    corrs = []
    for i in range(df1.shape[0]):
        corr = spearmanr(df1.iloc[i], df2.iloc[i]).correlation
        corrs.append(corr)
    return pd.Series(corrs, index=df1.index)

corrs_01 = rowwise_rank_corr(estimators[0].influence_estimate,
                             estimators[1].influence_estimate)
corrs_02 = rowwise_rank_corr(estimators[0].influence_estimate,
                             estimators[2].influence_estimate)
corrs_12 = rowwise_rank_corr(estimators[1].influence_estimate,
                             estimators[2].influence_estimate)


agreement = pd.DataFrame({
    "LESS_norm_vs_unorm": corrs_01,
    "LESS_norm_vs_DataInf": corrs_02,
    "LESS_unorm_vs_DataInf": corrs_12,
})

print(agreement.describe())

       LESS_norm_vs_unorm  LESS_norm_vs_DataInf  LESS_unorm_vs_DataInf
count         1000.000000           1000.000000            1000.000000
mean             0.909813              0.333481               0.513240
std              0.040334              0.156783               0.171884
min              0.734755             -0.158971              -0.106454
25%              0.893000              0.232858               0.414164
50%              0.912363              0.354583               0.555562
75%              0.930225              0.450131               0.637392
max              0.999620              0.661027               0.807110

In [5]:
# parser = argparse.ArgumentParser()
# parser.add_argument("--ratio", type=float, default=0.5, help="Ratio parameter for coreset")
# args = parser.parse_args([])



# base_model_path = "gpt2"
# train_dataset_path = "allenai/tulu-v2-sft-mixture"


# ft_model_name = os.path.basename(base_model_path) + "_" + os.path.basename(train_dataset_path) + "_" + str(args.ratio).replace(".","p")


# os.environ["WANDB_PROJECT"] = "cfe_finetuning"
# os.environ["WANDB_NAME"] = ft_model_name





# tokenizer = AutoTokenizer.from_pretrained(base_model_path)
# tokenizer.chat_template = "{{ bos_token }}{% for message in messages %}{% if message['role'] == 'system' %}{{ '<|system|>\n' + message['content'] + '\n' }}{% elif message['role'] == 'user' %}{{ '<|user|>\n' + message['content'] + '\n' }}{% elif message['role'] == 'assistant' %}{% if not loop.last %}{{ '<|assistant|>\n'  + message['content'] + eos_token + '\n' }}{% else %}{{ '<|assistant|>\n'  + message['content'] + eos_token }}{% endif %}{% endif %}{% if loop.last and add_generation_prompt %}{{ '<|assistant|>\n' }}{% endif %}{% endfor %}" # https://huggingface.co/allenai/OLMo-2-1124-7B-SFT/blob/main/tokenizer_config.json 
# lora_config = LoraConfig(
#     r=4,
#     lora_alpha=32,
#     target_modules=["c_attn", "q_proj", "v_proj"],
#     lora_dropout=0.1,
#     bias="none",
#     task_type=TaskType.CAUSAL_LM
# )
# model = AutoModelForCausalLM.from_pretrained(base_model_path)

# if tokenizer.pad_token is None:
#     tokenizer.pad_token = tokenizer.eos_token
# model.resize_token_embeddings(len(tokenizer))



# model = get_peft_model(model, lora_config)
# model.print_trainable_parameters()

# if hasattr(model, "enable_input_require_grads"):
#         model.enable_input_require_grads()
# else:
#         def make_inputs_require_grad(module, input, output):
#             output.requires_grad_(True)
#         model.get_input_embeddings().register_forward_hook(make_inputs_require_grad)


# # if training_args.data_selection_unit == "mezo" and training_args.efficient_mezo:
# # model.decomposer = DecomposedOlmo2(model)
# train_dataset = load_dataset(train_dataset_path, split="train[0:10]")

# def add_index(example, idx):
#     example["indices"] = idx
#     return example



# print(train_dataset)


# # tokenized_train = tokenize_dataset(train_dataset, tokenizer, max_lenght=1024)
# # tokenized_train = tokenized_train.map(add_index, with_indices=True)
# # data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
# torch.cuda.empty_cache()

In [6]:
%%writefile validation_engine.py
import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
import numpy as np
from datasets import load_dataset
from transformers import DataCollatorForLanguageModeling
from torch.cuda.amp import autocast
from tqdm import tqdm
import copy
from transformers import DataCollatorForLanguageModeling

class ChatTemplateCollator:
    def __init__(self, tokenizer, mlm=False, max_length=1024): # TODO
        self.tokenizer = tokenizer
        
        self.max_length = max_length
        self.base_collator = DataCollatorForLanguageModeling(
            tokenizer=tokenizer, mlm=mlm
        )

    def __call__(self, features):
        texts = [
            self.tokenizer.apply_chat_template(
                f["messages"], tokenize=False, add_generation_prompt=False
            )
            for f in features
        ]
        tokenized = self.tokenizer(
            texts,
            truncation=True,
            return_tensors="pt",
            padding=True,
            max_length=self.max_length
        )
 
        batch = [
            {"input_ids": tokenized["input_ids"][i],
             "attention_mask": tokenized["attention_mask"][i]}
            for i in range(len(tokenized["input_ids"]))
        ]
        return self.base_collator(batch)

class ValidationEngine():
    def __init__(self, base_model_path, device):
        self.base_model_path = base_model_path
        self.device = device
        self.tokenizer = AutoTokenizer.from_pretrained(self.base_model_path, padding_side='left')
        self.data_collator = ChatTemplateCollator(tokenizer=self.tokenizer, mlm=False)
        self.model_ = None
        if self.tokenizer.chat_template is None:
            self.tokenizer.chat_template = "{{ bos_token }}{% for message in messages %}{% if message['role'] == 'system' %}{{ '<|system|>\n' + message['content'] + '\n' }}{% elif message['role'] == 'user' %}{{ '<|user|>\n' + message['content'] + '\n' }}{% elif message['role'] == 'assistant' %}{% if not loop.last %}{{ '<|assistant|>\n'  + message['content'] + eos_token + '\n' }}{% else %}{{ '<|assistant|>\n'  + message['content'] + eos_token }}{% endif %}{% endif %}{% if loop.last and add_generation_prompt %}{{ '<|assistant|>\n' }}{% endif %}{% endfor %}" # https://huggingface.co/allenai/OLMo-2-1124-7B-SFT/blob/main/tokenizer_config.json 
        
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token # TODO
    def get_log_p(self, model, examples):
        batch = self.data_collator(examples)
        batch = {k: v.to(self.device) for k, v in batch.items()}
        with torch.no_grad(): 
            outputs = model.generate(**batch, max_new_tokens=5, return_dict_in_generate=True, output_scores=True,  num_beams=1)
            transition_scores = model.compute_transition_scores(
                outputs.sequences, outputs.scores, normalize_logits=True
            )
            log_p = transition_scores.sum(axis=1)
            # print("log_p",log_p)
            return log_p
    @property
    def model(self):
        if self.model_ is None:
            self.model_ = AutoModelForCausalLM.from_pretrained(self.base_model_path,torch_dtype=torch.float32).to(self.device)
            # self.model_.generation_config.use_cache = True
        return self.model_
    def score(self, train_dataset, test_sets):
        deltas = []
        model_ft = AutoModelForCausalLM.from_pretrained(self.base_model_path, torch_dtype=torch.float32).to(self.device)
        model_ft = self.finetune(model_ft, train_dataset)
        for test_dataset in test_sets:
            log_p_before_ft = self.get_log_p(self.model, test_dataset)       
            log_p_after_ft = self.get_log_p(model_ft, test_dataset)
            deltas.append(log_p_after_ft - log_p_before_ft)
        return deltas
    def finetune(self, model, train_dataset):
        training_args = TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=1,
        remove_unused_columns=False,
        num_train_epochs=5,
        learning_rate=2e-5,
        logging_steps=500,
        seed=42,
        #save_steps=None,#100,
        # save_total_limit=2,
        #  fp16=True, 
        #   bf16=True,
        report_to=[],
        disable_tqdm=True 
        )
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            processing_class=self.tokenizer,
            data_collator=self.data_collator,
        )
        

        trainer.train(resume_from_checkpoint=False)
        return model

Overwriting validation_engine.py

In [7]:
%%writefile validation_worker.py
import os
import torch
from tqdm import tqdm
CACHE_DIR = "./cache/validation/"


def process(batch, gpu_id):
    """
    Worker function to process a batch of test sets on a specific GPU.
    """
    os.makedirs(CACHE_DIR,exist_ok=True)
    try:
        # Restrict this process to a single GPU
        os.environ["CUDA_VISIBLE_DEVICES"] = str(gpu_id)
        import torch
        from validation_engine import ValidationEngine  # import inside worker

        engine = ValidationEngine("EleutherAI/pythia-31m", device="cuda:0")
        results = []
        for ts_batch, test_sets, test_indices, estimator, explanation_type in tqdm(batch, desc=f"GPU {gpu_id}", leave=False,position=gpu_id):
          
            deltas =  [engine.score(explanation, test_sets) for (setting, explanation) in ts_batch]
            results.append([(setting,
                             estimator.get_config_string().replace(" ",""), # estimator
                             explanation,
                             explanation_type, # type
                             test_indices, 
                             delta[0].item(),
                             ) for (setting, explanation), delta in zip(ts_batch, deltas)])
        return results

    except Exception as e:
        import traceback, logging
        logging.error(f"Error in process for GPU {gpu_id}: {e}")
        logging.error(traceback.format_exc())
        raise

Overwriting validation_worker.py

In [8]:
import logging
from concurrent.futures import ProcessPoolExecutor, as_completed
import torch
import multiprocessing
from explanations import TopKMostInfluential, TopKLeastInfluential, TopKMostOrthogonal, TopKLeastOrthogonal
from tqdm import tqdm
import itertools
import pandas as pd
import traceback

import evaluation_worker

logging.basicConfig(level=logging.ERROR, format='%(asctime)s [%(levelname)s] %(message)s')
multiprocessing.set_start_method('spawn', force=True)
torch.manual_seed(42)


n_test = 10
test_indices = test_dataset.shuffle(seed=42).select(range(n_test))["indices"]

num_devices = torch.cuda.device_count()

explanation_types = [TopKMostInfluential, TopKLeastInfluential, TopKMostOrthogonal, TopKLeastOrthogonal]

In [9]:
import logging
from concurrent.futures import ProcessPoolExecutor, as_completed
import torch
import multiprocessing
from validation_worker import process

logging.basicConfig(level=logging.ERROR, format='%(asctime)s [%(levelname)s] %(message)s')

multiprocessing.set_start_method('spawn', force=True)

num_gpus = torch.cuda.device_count()
logging.info(f"Detected {num_gpus} GPUs")

[INFO] Detected 2 GPUs

In [10]:
results = []
test_sets = []
for estimator in estimators:
    for explanation_type in explanation_types:
        explanations = estimator.influence_estimate.iloc[test_indices].apply(
                lambda row: explanation_type(row.name, estimator), axis=1
            )
        documents = [e.documents for e in explanations]
        test_indices = [e.dataset_idx for e in explanations]
        test_sets.extend([(
            ((("explanation", train_dataset.select(e))),
            ("random", train_dataset.shuffle(seed=seed).select(range(len(e)))),
            ),
            [test_dataset.select([idx])], [[idx]], estimator, explanation_type) for seed, (e,idx) in enumerate(zip(documents,test_indices))
        ])

batch_size = max(len(test_sets) // num_gpus, 1)
batches = [test_sets[i:i + batch_size] for i in range(0, len(test_sets), batch_size)]
      

with ProcessPoolExecutor(max_workers=num_gpus) as executor:
    futures = [executor.submit(process, batch, i % num_gpus) for i, batch in enumerate(batches)]
    
    for future in as_completed(futures):
        try:
            results.extend(future.result())
        except Exception as e:
            logging.error(f"A future failed: {e}")


#     break
# break

logging.info("All batches processed")

GPU 0:   0%|          | 0/60 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:   2%|▏         | 1/60 [00:17<16:43, 17.01s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:   2%|▏         | 1/60 [00:19<19:03, 19.38s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:   3%|▎         | 2/60 [00:31<15:00, 15.53s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:   3%|▎         | 2/60 [00:34<16:12, 16.76s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:   5%|▌         | 3/60 [00:44<13:47, 14.52s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:   5%|▌         | 3/60 [00:48<14:52, 15.65s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:   7%|▋         | 4/60 [00:59<13:30, 14.47s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:   7%|▋         | 4/60 [01:03<14:08, 15.16s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:   8%|▊         | 5/60 [01:13<13:08, 14.33s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:   8%|▊         | 5/60 [01:17<13:39, 14.90s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  10%|█         | 6/60 [01:28<13:04, 14.53s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  10%|█         | 6/60 [01:31<13:00, 14.45s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  12%|█▏        | 7/60 [01:41<12:30, 14.17s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  12%|█▏        | 7/60 [01:45<12:44, 14.42s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  13%|█▎        | 8/60 [01:56<12:20, 14.25s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  13%|█▎        | 8/60 [02:00<12:40, 14.62s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  15%|█▌        | 9/60 [02:10<12:03, 14.18s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  15%|█▌        | 9/60 [02:14<12:21, 14.53s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  17%|█▋        | 10/60 [02:24<11:56, 14.33s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  17%|█▋        | 10/60 [02:28<11:54, 14.28s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  18%|█▊        | 11/60 [02:38<11:40, 14.29s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  18%|█▊        | 11/60 [02:42<11:37, 14.23s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  20%|██        | 12/60 [02:54<11:38, 14.55s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  20%|██        | 12/60 [02:56<11:23, 14.24s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  22%|██▏       | 13/60 [03:08<11:19, 14.46s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  22%|██▏       | 13/60 [03:11<11:12, 14.31s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  23%|██▎       | 14/60 [03:22<11:06, 14.49s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  23%|██▎       | 14/60 [03:25<10:59, 14.33s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  25%|██▌       | 15/60 [03:37<10:48, 14.41s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  25%|██▌       | 15/60 [03:39<10:42, 14.29s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  27%|██▋       | 16/60 [03:51<10:31, 14.35s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  27%|██▋       | 16/60 [03:54<10:27, 14.26s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  28%|██▊       | 17/60 [04:05<10:12, 14.25s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  28%|██▊       | 17/60 [04:08<10:12, 14.24s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  30%|███       | 18/60 [04:18<09:50, 14.05s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  30%|███       | 18/60 [04:22<09:59, 14.26s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  32%|███▏      | 19/60 [04:33<09:46, 14.30s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  32%|███▏      | 19/60 [04:36<09:41, 14.19s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  33%|███▎      | 20/60 [04:48<09:31, 14.28s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  33%|███▎      | 20/60 [04:50<09:27, 14.19s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  35%|███▌      | 21/60 [05:02<09:18, 14.32s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  35%|███▌      | 21/60 [05:05<09:16, 14.27s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  37%|███▋      | 22/60 [05:16<09:04, 14.32s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  37%|███▋      | 22/60 [05:19<09:02, 14.26s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  38%|███▊      | 23/60 [05:31<08:53, 14.42s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  38%|███▊      | 23/60 [05:34<08:51, 14.37s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  40%|████      | 24/60 [05:46<08:48, 14.68s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  40%|████      | 24/60 [05:49<08:45, 14.59s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  42%|████▏     | 25/60 [06:02<08:40, 14.86s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  42%|████▏     | 25/60 [06:04<08:36, 14.77s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  43%|████▎     | 26/60 [06:18<08:38, 15.25s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  43%|████▎     | 26/60 [06:20<08:36, 15.20s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  45%|████▌     | 27/60 [06:33<08:21, 15.21s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  45%|████▌     | 27/60 [06:35<08:21, 15.20s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  47%|████▋     | 28/60 [06:47<07:58, 14.97s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  47%|████▋     | 28/60 [06:50<08:01, 15.03s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  48%|████▊     | 29/60 [07:01<07:31, 14.55s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  48%|████▊     | 29/60 [07:04<07:40, 14.84s/it]

{'train_runtime': 6.6736, 'train_samples_per_second': 7.492, 'train_steps_per_second': 7.492, 'train_loss': 2.511186370849609, 'epoch': 5.0}
{'train_runtime': 6.2901, 'train_samples_per_second': 7.949, 'train_steps_per_second': 7.949, 'train_loss': 2.3392115783691407, 'epoch': 5.0}
{'train_runtime': 6.1442, 'train_samples_per_second': 8.138, 'train_steps_per_second': 8.138, 'train_loss': 2.5912884521484374, 'epoch': 5.0}
{'train_runtime': 5.8908, 'train_samples_per_second': 8.488, 'train_steps_per_second': 8.488, 'train_loss': 2.529496917724609, 'epoch': 5.0}
{'train_runtime': 4.9895, 'train_samples_per_second': 10.021, 'train_steps_per_second': 10.021, 'train_loss': 2.8594741821289062, 'epoch': 5.0}
{'train_runtime': 5.6432, 'train_samples_per_second': 8.86, 'train_steps_per_second': 8.86, 'train_loss': 2.4237994384765624, 'epoch': 5.0}
{'train_runtime': 5.6077, 'train_samples_per_second': 8.916, 'train_steps_per_second': 8.916, 'train_loss': 2.8812945556640623, 'epoch': 5.0}
{'train_runtime': 5.591, 'train_samples_per_second': 8.943, 'train_steps_per_second': 8.943, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 5.4992, 'train_samples_per_second': 9.092, 'train_steps_per_second': 9.092, 'train_loss': 2.560130310058594, 'epoch': 5.0}
{'train_runtime': 5.7491, 'train_samples_per_second': 8.697, 'train_steps_per_second': 8.697, 'train_loss': 2.569183349609375, 'epoch': 5.0}
{'train_runtime': 5.4752, 'train_samples_per_second': 9.132, 'train_steps_per_second': 9.132, 'train_loss': 1.9578857421875, 'epoch': 5.0}
{'train_runtime': 6.3693, 'train_samples_per_second': 7.85, 'train_steps_per_second': 7.85, 'train_loss': 2.1473020935058593, 'epoch': 5.0}
{'train_runtime': 5.4325, 'train_samples_per_second': 9.204, 'train_steps_per_second': 9.204, 'train_loss': 2.3190875244140625, 'epoch': 5.0}
{'train_runtime': 5.687, 'train_samples_per_second': 8.792, 'train_steps_per_second': 8.792, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 5.7931, 'train_samples_per_second': 8.631, 'train_steps_per_second': 8.631, 'train_loss': 2.682675476074219, 'epoch': 5.0}
{'train_runtime': 5.6599, 'train_samples_per_second': 8.834, 'train_steps_per_second': 8.834, 'train_loss': 2.767037048339844, 'epoch': 5.0}
{'train_runtime': 5.5563, 'train_samples_per_second': 8.999, 'train_steps_per_second': 8.999, 'train_loss': 2.310517120361328, 'epoch': 5.0}
{'train_runtime': 5.5826, 'train_samples_per_second': 8.956, 'train_steps_per_second': 8.956, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 5.7029, 'train_samples_per_second': 8.767, 'train_steps_per_second': 8.767, 'train_loss': 2.7805224609375, 'epoch': 5.0}
{'train_runtime': 6.6098, 'train_samples_per_second': 7.565, 'train_steps_per_second': 7.565, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 5.8408, 'train_samples_per_second': 8.56, 'train_steps_per_second': 8.56, 'train_loss': 2.593852233886719, 'epoch': 5.0}
{'train_runtime': 5.587, 'train_samples_per_second': 8.949, 'train_steps_per_second': 8.949, 'train_loss': 2.3444366455078125, 'epoch': 5.0}
{'train_runtime': 6.4488, 'train_samples_per_second': 7.753, 'train_steps_per_second': 7.753, 'train_loss': 2.6160626220703125, 'epoch': 5.0}
{'train_runtime': 5.8294, 'train_samples_per_second': 8.577, 'train_steps_per_second': 8.577, 'train_loss': 2.535386810302734, 'epoch': 5.0}
{'train_runtime': 6.6179, 'train_samples_per_second': 7.555, 'train_steps_per_second': 7.555, 'train_loss': 2.678212890625, 'epoch': 5.0}
{'train_runtime': 5.5701, 'train_samples_per_second': 8.976, 'train_steps_per_second': 8.976, 'train_loss': 2.418035430908203, 'epoch': 5.0}
{'train_runtime': 6.377, 'train_samples_per_second': 7.841, 'train_steps_per_second': 7.841, 'train_loss': 2.6537237548828125, 'epoch': 5.0}
{'train_runtime': 5.7738, 'train_samples_per_second': 8.66, 'train_steps_per_second': 8.66, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 6.2407, 'train_samples_per_second': 8.012, 'train_steps_per_second': 8.012, 'train_loss': 2.7099267578125, 'epoch': 5.0}
{'train_runtime': 6.2668, 'train_samples_per_second': 7.979, 'train_steps_per_second': 7.979, 'train_loss': 2.5881719970703125, 'epoch': 5.0}
{'train_runtime': 6.2515, 'train_samples_per_second': 7.998, 'train_steps_per_second': 7.998, 'train_loss': 2.6541375732421875, 'epoch': 5.0}
{'train_runtime': 6.145, 'train_samples_per_second': 8.137, 'train_steps_per_second': 8.137, 'train_loss': 2.1440257263183593, 'epoch': 5.0}
{'train_runtime': 6.2494, 'train_samples_per_second': 8.001, 'train_steps_per_second': 8.001, 'train_loss': 2.5844845581054687, 'epoch': 5.0}
{'train_runtime': 6.0679, 'train_samples_per_second': 8.24, 'train_steps_per_second': 8.24, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 5.4245, 'train_samples_per_second': 9.217, 'train_steps_per_second': 9.217, 'train_loss': 2.507269287109375, 'epoch': 5.0}
{'train_runtime': 5.6635, 'train_samples_per_second': 8.828, 'train_steps_per_second': 8.828, 'train_loss': 2.7626202392578123, 'epoch': 5.0}
{'train_runtime': 6.486, 'train_samples_per_second': 7.709, 'train_steps_per_second': 7.709, 'train_loss': 2.6819168090820313, 'epoch': 5.0}
{'train_runtime': 6.1199, 'train_samples_per_second': 8.17, 'train_steps_per_second': 8.17, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 6.2523, 'train_samples_per_second': 7.997, 'train_steps_per_second': 7.997, 'train_loss': 2.6429843139648437, 'epoch': 5.0}
{'train_runtime': 6.249, 'train_samples_per_second': 8.001, 'train_steps_per_second': 8.001, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 6.4448, 'train_samples_per_second': 7.758, 'train_steps_per_second': 7.758, 'train_loss': 2.593852233886719, 'epoch': 5.0}
{'train_runtime': 5.7576, 'train_samples_per_second': 8.684, 'train_steps_per_second': 8.684, 'train_loss': 2.336927795410156, 'epoch': 5.0}
{'train_runtime': 6.2856, 'train_samples_per_second': 7.955, 'train_steps_per_second': 7.955, 'train_loss': 2.6160626220703125, 'epoch': 5.0}
{'train_runtime': 6.2442, 'train_samples_per_second': 8.007, 'train_steps_per_second': 8.007, 'train_loss': 2.52403564453125, 'epoch': 5.0}
{'train_runtime': 6.5806, 'train_samples_per_second': 7.598, 'train_steps_per_second': 7.598, 'train_loss': 2.6782025146484374, 'epoch': 5.0}
{'train_runtime': 5.8378, 'train_samples_per_second': 8.565, 'train_steps_per_second': 8.565, 'train_loss': 2.423096923828125, 'epoch': 5.0}
{'train_runtime': 6.5741, 'train_samples_per_second': 7.606, 'train_steps_per_second': 7.606, 'train_loss': 2.6536834716796873, 'epoch': 5.0}
{'train_runtime': 6.2724, 'train_samples_per_second': 7.971, 'train_steps_per_second': 7.971, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 6.6733, 'train_samples_per_second': 7.493, 'train_steps_per_second': 7.493, 'train_loss': 2.7099267578125, 'epoch': 5.0}
{'train_runtime': 6.0979, 'train_samples_per_second': 8.2, 'train_steps_per_second': 8.2, 'train_loss': 2.57, 'epoch': 5.0}
{'train_runtime': 6.709, 'train_samples_per_second': 7.453, 'train_steps_per_second': 7.453, 'train_loss': 2.6541375732421875, 'epoch': 5.0}
{'train_runtime': 6.1946, 'train_samples_per_second': 8.072, 'train_steps_per_second': 8.072, 'train_loss': 2.148734283447266, 'epoch': 5.0}
{'train_runtime': 6.5021, 'train_samples_per_second': 7.69, 'train_steps_per_second': 7.69, 'train_loss': 2.5844845581054687, 'epoch': 5.0}
{'train_runtime': 6.0053, 'train_samples_per_second': 8.326, 'train_steps_per_second': 8.326, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 5.927, 'train_samples_per_second': 8.436, 'train_steps_per_second': 8.436, 'train_loss': 2.507269287109375, 'epoch': 5.0}
{'train_runtime': 6.5035, 'train_samples_per_second': 7.688, 'train_steps_per_second': 7.688, 'train_loss': 2.7663192749023438, 'epoch': 5.0}
{'train_runtime': 6.4127, 'train_samples_per_second': 7.797, 'train_steps_per_second': 7.797, 'train_loss': 2.6819168090820313, 'epoch': 5.0}
{'train_runtime': 5.0997, 'train_samples_per_second': 9.805, 'train_steps_per_second': 9.805, 'train_loss': 2.3514976501464844, 'epoch': 5.0}

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

{'train_runtime': 8.9777, 'train_samples_per_second': 5.569, 'train_steps_per_second': 5.569, 'train_loss': 2.7346670532226565, 'epoch': 5.0}
{'train_runtime': 7.1623, 'train_samples_per_second': 6.981, 'train_steps_per_second': 6.981, 'train_loss': 2.3523313903808596, 'epoch': 5.0}
{'train_runtime': 6.8947, 'train_samples_per_second': 7.252, 'train_steps_per_second': 7.252, 'train_loss': 2.672760009765625, 'epoch': 5.0}
{'train_runtime': 5.6983, 'train_samples_per_second': 8.775, 'train_steps_per_second': 8.775, 'train_loss': 2.5161984252929686, 'epoch': 5.0}
{'train_runtime': 6.3871, 'train_samples_per_second': 7.828, 'train_steps_per_second': 7.828, 'train_loss': 2.6475540161132813, 'epoch': 5.0}
{'train_runtime': 5.3299, 'train_samples_per_second': 9.381, 'train_steps_per_second': 9.381, 'train_loss': 2.419933166503906, 'epoch': 5.0}
{'train_runtime': 5.6533, 'train_samples_per_second': 8.844, 'train_steps_per_second': 8.844, 'train_loss': 2.665640563964844, 'epoch': 5.0}
{'train_runtime': 5.7515, 'train_samples_per_second': 8.693, 'train_steps_per_second': 8.693, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 6.3753, 'train_samples_per_second': 7.843, 'train_steps_per_second': 7.843, 'train_loss': 2.677030334472656, 'epoch': 5.0}
{'train_runtime': 5.7982, 'train_samples_per_second': 8.623, 'train_steps_per_second': 8.623, 'train_loss': 2.5642340087890627, 'epoch': 5.0}
{'train_runtime': 5.4926, 'train_samples_per_second': 9.103, 'train_steps_per_second': 9.103, 'train_loss': 2.7035861206054688, 'epoch': 5.0}
{'train_runtime': 5.673, 'train_samples_per_second': 8.814, 'train_steps_per_second': 8.814, 'train_loss': 2.1359881591796874, 'epoch': 5.0}
{'train_runtime': 6.5338, 'train_samples_per_second': 7.653, 'train_steps_per_second': 7.653, 'train_loss': 2.5963677978515625, 'epoch': 5.0}
{'train_runtime': 5.092, 'train_samples_per_second': 9.819, 'train_steps_per_second': 9.819, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 5.6992, 'train_samples_per_second': 8.773, 'train_steps_per_second': 8.773, 'train_loss': 2.444275665283203, 'epoch': 5.0}
{'train_runtime': 6.4155, 'train_samples_per_second': 7.794, 'train_steps_per_second': 7.794, 'train_loss': 2.76525390625, 'epoch': 5.0}
{'train_runtime': 6.1536, 'train_samples_per_second': 8.125, 'train_steps_per_second': 8.125, 'train_loss': 2.675413818359375, 'epoch': 5.0}
{'train_runtime': 5.7563, 'train_samples_per_second': 8.686, 'train_steps_per_second': 8.686, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 6.5153, 'train_samples_per_second': 7.674, 'train_steps_per_second': 7.674, 'train_loss': 2.6587396240234376, 'epoch': 5.0}
{'train_runtime': 4.9743, 'train_samples_per_second': 10.052, 'train_steps_per_second': 10.052, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 5.9557, 'train_samples_per_second': 8.395, 'train_steps_per_second': 8.395, 'train_loss': 2.4106700134277346, 'epoch': 5.0}
{'train_runtime': 5.4128, 'train_samples_per_second': 9.237, 'train_steps_per_second': 9.237, 'train_loss': 2.3444477844238283, 'epoch': 5.0}
{'train_runtime': 5.6618, 'train_samples_per_second': 8.831, 'train_steps_per_second': 8.831, 'train_loss': 2.454573059082031, 'epoch': 5.0}
{'train_runtime': 5.5946, 'train_samples_per_second': 8.937, 'train_steps_per_second': 8.937, 'train_loss': 2.5084474182128904, 'epoch': 5.0}
{'train_runtime': 6.3299, 'train_samples_per_second': 7.899, 'train_steps_per_second': 7.899, 'train_loss': 2.7464865112304686, 'epoch': 5.0}
{'train_runtime': 5.5621, 'train_samples_per_second': 8.989, 'train_steps_per_second': 8.989, 'train_loss': 2.418736877441406, 'epoch': 5.0}
{'train_runtime': 6.0698, 'train_samples_per_second': 8.237, 'train_steps_per_second': 8.237, 'train_loss': 2.841162109375, 'epoch': 5.0}
{'train_runtime': 5.7219, 'train_samples_per_second': 8.738, 'train_steps_per_second': 8.738, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 5.5173, 'train_samples_per_second': 9.062, 'train_steps_per_second': 9.062, 'train_loss': 2.366075439453125, 'epoch': 5.0}
{'train_runtime': 5.7393, 'train_samples_per_second': 8.712, 'train_steps_per_second': 8.712, 'train_loss': 2.5584861755371096, 'epoch': 5.0}
{'train_runtime': 5.667, 'train_samples_per_second': 8.823, 'train_steps_per_second': 8.823, 'train_loss': 1.964340362548828, 'epoch': 5.0}
{'train_runtime': 5.7267, 'train_samples_per_second': 8.731, 'train_steps_per_second': 8.731, 'train_loss': 2.145385284423828, 'epoch': 5.0}
{'train_runtime': 5.7186, 'train_samples_per_second': 8.743, 'train_steps_per_second': 8.743, 'train_loss': 1.8405987548828124, 'epoch': 5.0}
{'train_runtime': 5.5782, 'train_samples_per_second': 8.964, 'train_steps_per_second': 8.964, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 5.8017, 'train_samples_per_second': 8.618, 'train_steps_per_second': 8.618, 'train_loss': 2.7567929077148436, 'epoch': 5.0}
{'train_runtime': 5.6145, 'train_samples_per_second': 8.906, 'train_steps_per_second': 8.906, 'train_loss': 2.765685729980469, 'epoch': 5.0}
{'train_runtime': 5.608, 'train_samples_per_second': 8.916, 'train_steps_per_second': 8.916, 'train_loss': 2.341680450439453, 'epoch': 5.0}
{'train_runtime': 5.5521, 'train_samples_per_second': 9.006, 'train_steps_per_second': 9.006, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 5.7138, 'train_samples_per_second': 8.751, 'train_steps_per_second': 8.751, 'train_loss': 2.71467529296875, 'epoch': 5.0}
{'train_runtime': 5.6086, 'train_samples_per_second': 8.915, 'train_steps_per_second': 8.915, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 6.1026, 'train_samples_per_second': 8.193, 'train_steps_per_second': 8.193, 'train_loss': 3.5120574951171877, 'epoch': 5.0}
{'train_runtime': 5.7011, 'train_samples_per_second': 8.77, 'train_steps_per_second': 8.77, 'train_loss': 2.3346295166015625, 'epoch': 5.0}
{'train_runtime': 5.548, 'train_samples_per_second': 9.012, 'train_steps_per_second': 9.012, 'train_loss': 3.472654113769531, 'epoch': 5.0}
{'train_runtime': 5.6891, 'train_samples_per_second': 8.789, 'train_steps_per_second': 8.789, 'train_loss': 2.511149139404297, 'epoch': 5.0}
{'train_runtime': 6.5888, 'train_samples_per_second': 7.589, 'train_steps_per_second': 7.589, 'train_loss': 2.461853790283203, 'epoch': 5.0}
{'train_runtime': 5.6951, 'train_samples_per_second': 8.78, 'train_steps_per_second': 8.78, 'train_loss': 2.421764068603516, 'epoch': 5.0}
{'train_runtime': 6.5863, 'train_samples_per_second': 7.592, 'train_steps_per_second': 7.592, 'train_loss': 2.7254983520507814, 'epoch': 5.0}
{'train_runtime': 6.773, 'train_samples_per_second': 7.382, 'train_steps_per_second': 7.382, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 6.847, 'train_samples_per_second': 7.302, 'train_steps_per_second': 7.302, 'train_loss': 3.2928485107421874, 'epoch': 5.0}
{'train_runtime': 6.6186, 'train_samples_per_second': 7.555, 'train_steps_per_second': 7.555, 'train_loss': 2.568310546875, 'epoch': 5.0}
{'train_runtime': 7.243, 'train_samples_per_second': 6.903, 'train_steps_per_second': 6.903, 'train_loss': 2.6188955688476563, 'epoch': 5.0}
{'train_runtime': 7.1493, 'train_samples_per_second': 6.994, 'train_steps_per_second': 6.994, 'train_loss': 2.1466294860839845, 'epoch': 5.0}
{'train_runtime': 6.9485, 'train_samples_per_second': 7.196, 'train_steps_per_second': 7.196, 'train_loss': 3.048661193847656, 'epoch': 5.0}
{'train_runtime': 6.5547, 'train_samples_per_second': 7.628, 'train_steps_per_second': 7.628, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 6.1287, 'train_samples_per_second': 8.158, 'train_steps_per_second': 8.158, 'train_loss': 3.0427398681640625, 'epoch': 5.0}
{'train_runtime': 6.0596, 'train_samples_per_second': 8.251, 'train_steps_per_second': 8.251, 'train_loss': 2.769599609375, 'epoch': 5.0}
{'train_runtime': 6.0442, 'train_samples_per_second': 8.272, 'train_steps_per_second': 8.272, 'train_loss': 2.035836486816406, 'epoch': 5.0}
{'train_runtime': 5.6599, 'train_samples_per_second': 8.834, 'train_steps_per_second': 8.834, 'train_loss': 2.3514976501464844, 'epoch': 5.0}

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  50%|█████     | 30/60 [07:16<07:19, 14.64s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  50%|█████     | 30/60 [07:19<07:18, 14.63s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  52%|█████▏    | 31/60 [07:29<06:53, 14.27s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  52%|█████▏    | 31/60 [07:33<07:06, 14.72s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  53%|█████▎    | 32/60 [07:43<06:38, 14.22s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  53%|█████▎    | 32/60 [07:48<06:47, 14.57s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  55%|█████▌    | 33/60 [07:58<06:25, 14.29s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  55%|█████▌    | 33/60 [08:02<06:33, 14.56s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  57%|█████▋    | 34/60 [08:13<06:19, 14.58s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  57%|█████▋    | 34/60 [08:16<06:09, 14.20s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  58%|█████▊    | 35/60 [08:26<05:55, 14.23s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  58%|█████▊    | 35/60 [08:31<06:02, 14.50s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  60%|██████    | 36/60 [08:40<05:41, 14.23s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  60%|██████    | 36/60 [08:45<05:45, 14.38s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  62%|██████▏   | 37/60 [08:55<05:27, 14.23s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  62%|██████▏   | 37/60 [08:58<05:24, 14.12s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  63%|██████▎   | 38/60 [09:09<05:12, 14.22s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  63%|██████▎   | 38/60 [09:13<05:17, 14.41s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  65%|██████▌   | 39/60 [09:24<05:01, 14.37s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  65%|██████▌   | 39/60 [09:28<05:04, 14.51s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  67%|██████▋   | 40/60 [09:38<04:46, 14.33s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  67%|██████▋   | 40/60 [09:42<04:47, 14.40s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  68%|██████▊   | 41/60 [09:52<04:31, 14.30s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  68%|██████▊   | 41/60 [09:57<04:32, 14.36s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  70%|███████   | 42/60 [10:06<04:17, 14.31s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  70%|███████   | 42/60 [10:11<04:17, 14.32s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  72%|███████▏  | 43/60 [10:21<04:03, 14.30s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  72%|███████▏  | 43/60 [10:25<04:04, 14.37s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  73%|███████▎  | 44/60 [10:35<03:50, 14.40s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  73%|███████▎  | 44/60 [10:40<03:51, 14.50s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  75%|███████▌  | 45/60 [10:50<03:37, 14.49s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  75%|███████▌  | 45/60 [10:55<03:37, 14.50s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  77%|███████▋  | 46/60 [11:04<03:22, 14.43s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  77%|███████▋  | 46/60 [11:09<03:21, 14.37s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  78%|███████▊  | 47/60 [11:19<03:06, 14.35s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  78%|███████▊  | 47/60 [11:23<03:07, 14.45s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  80%|████████  | 48/60 [11:33<02:53, 14.42s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  80%|████████  | 48/60 [11:38<02:52, 14.37s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  82%|████████▏ | 49/60 [11:47<02:37, 14.34s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  82%|████████▏ | 49/60 [11:52<02:37, 14.31s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  83%|████████▎ | 50/60 [12:01<02:23, 14.30s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  83%|████████▎ | 50/60 [12:05<02:20, 14.05s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  85%|████████▌ | 51/60 [12:17<02:10, 14.53s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  85%|████████▌ | 51/60 [12:19<02:06, 14.10s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  87%|████████▋ | 52/60 [12:30<01:53, 14.22s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  87%|████████▋ | 52/60 [12:34<01:53, 14.14s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  88%|████████▊ | 53/60 [12:45<01:41, 14.45s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  88%|████████▊ | 53/60 [12:48<01:38, 14.14s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  90%|█████████ | 54/60 [12:59<01:26, 14.37s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  90%|█████████ | 54/60 [13:02<01:24, 14.16s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  92%|█████████▏| 55/60 [13:13<01:11, 14.32s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  92%|█████████▏| 55/60 [13:16<01:10, 14.19s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  93%|█████████▎| 56/60 [13:28<00:57, 14.38s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  93%|█████████▎| 56/60 [13:31<00:56, 14.22s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  95%|█████████▌| 57/60 [13:42<00:43, 14.43s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  95%|█████████▌| 57/60 [13:45<00:43, 14.39s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  97%|█████████▋| 58/60 [13:57<00:28, 14.36s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  97%|█████████▋| 58/60 [14:00<00:28, 14.34s/it]

{'train_runtime': 6.5285, 'train_samples_per_second': 7.659, 'train_steps_per_second': 7.659, 'train_loss': 2.6429843139648437, 'epoch': 5.0}
{'train_runtime': 6.0623, 'train_samples_per_second': 8.248, 'train_steps_per_second': 8.248, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 5.3673, 'train_samples_per_second': 9.316, 'train_steps_per_second': 9.316, 'train_loss': 2.511186370849609, 'epoch': 5.0}
{'train_runtime': 5.6628, 'train_samples_per_second': 8.83, 'train_steps_per_second': 8.83, 'train_loss': 2.3275494384765625, 'epoch': 5.0}
{'train_runtime': 5.619, 'train_samples_per_second': 8.898, 'train_steps_per_second': 8.898, 'train_loss': 2.5912884521484374, 'epoch': 5.0}
{'train_runtime': 5.6299, 'train_samples_per_second': 8.881, 'train_steps_per_second': 8.881, 'train_loss': 2.5087632751464843, 'epoch': 5.0}
{'train_runtime': 5.7362, 'train_samples_per_second': 8.717, 'train_steps_per_second': 8.717, 'train_loss': 2.8594741821289062, 'epoch': 5.0}
{'train_runtime': 6.1266, 'train_samples_per_second': 8.161, 'train_steps_per_second': 8.161, 'train_loss': 2.4165155029296876, 'epoch': 5.0}
{'train_runtime': 5.9566, 'train_samples_per_second': 8.394, 'train_steps_per_second': 8.394, 'train_loss': 2.8812945556640623, 'epoch': 5.0}
{'train_runtime': 6.4046, 'train_samples_per_second': 7.807, 'train_steps_per_second': 7.807, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 5.3052, 'train_samples_per_second': 9.425, 'train_steps_per_second': 9.425, 'train_loss': 2.560130310058594, 'epoch': 5.0}
{'train_runtime': 5.6493, 'train_samples_per_second': 8.851, 'train_steps_per_second': 8.851, 'train_loss': 2.5642654418945314, 'epoch': 5.0}
{'train_runtime': 5.745, 'train_samples_per_second': 8.703, 'train_steps_per_second': 8.703, 'train_loss': 1.9578857421875, 'epoch': 5.0}
{'train_runtime': 5.8835, 'train_samples_per_second': 8.498, 'train_steps_per_second': 8.498, 'train_loss': 2.14194580078125, 'epoch': 5.0}
{'train_runtime': 5.6219, 'train_samples_per_second': 8.894, 'train_steps_per_second': 8.894, 'train_loss': 2.3190875244140625, 'epoch': 5.0}
{'train_runtime': 5.7273, 'train_samples_per_second': 8.73, 'train_steps_per_second': 8.73, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 5.7709, 'train_samples_per_second': 8.664, 'train_steps_per_second': 8.664, 'train_loss': 2.682675476074219, 'epoch': 5.0}
{'train_runtime': 5.6059, 'train_samples_per_second': 8.919, 'train_steps_per_second': 8.919, 'train_loss': 2.7626129150390626, 'epoch': 5.0}
{'train_runtime': 5.5734, 'train_samples_per_second': 8.971, 'train_steps_per_second': 8.971, 'train_loss': 2.310517120361328, 'epoch': 5.0}
{'train_runtime': 6.7051, 'train_samples_per_second': 7.457, 'train_steps_per_second': 7.457, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 5.5467, 'train_samples_per_second': 9.014, 'train_steps_per_second': 9.014, 'train_loss': 2.778363037109375, 'epoch': 5.0}
{'train_runtime': 5.7062, 'train_samples_per_second': 8.762, 'train_steps_per_second': 8.762, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 5.661, 'train_samples_per_second': 8.832, 'train_steps_per_second': 8.832, 'train_loss': 2.4106700134277346, 'epoch': 5.0}
{'train_runtime': 6.0421, 'train_samples_per_second': 8.275, 'train_steps_per_second': 8.275, 'train_loss': 2.340654754638672, 'epoch': 5.0}
{'train_runtime': 5.633, 'train_samples_per_second': 8.876, 'train_steps_per_second': 8.876, 'train_loss': 2.454573059082031, 'epoch': 5.0}
{'train_runtime': 5.6563, 'train_samples_per_second': 8.84, 'train_steps_per_second': 8.84, 'train_loss': 2.5202392578125, 'epoch': 5.0}
{'train_runtime': 5.5863, 'train_samples_per_second': 8.95, 'train_steps_per_second': 8.95, 'train_loss': 2.7464865112304686, 'epoch': 5.0}
{'train_runtime': 5.5909, 'train_samples_per_second': 8.943, 'train_steps_per_second': 8.943, 'train_loss': 2.4172125244140625, 'epoch': 5.0}
{'train_runtime': 5.7387, 'train_samples_per_second': 8.713, 'train_steps_per_second': 8.713, 'train_loss': 2.841162109375, 'epoch': 5.0}
{'train_runtime': 6.6915, 'train_samples_per_second': 7.472, 'train_steps_per_second': 7.472, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 5.9848, 'train_samples_per_second': 8.355, 'train_steps_per_second': 8.355, 'train_loss': 2.366075439453125, 'epoch': 5.0}
{'train_runtime': 6.623, 'train_samples_per_second': 7.549, 'train_steps_per_second': 7.549, 'train_loss': 2.5740887451171877, 'epoch': 5.0}
{'train_runtime': 5.7621, 'train_samples_per_second': 8.677, 'train_steps_per_second': 8.677, 'train_loss': 1.964340362548828, 'epoch': 5.0}
{'train_runtime': 5.7596, 'train_samples_per_second': 8.681, 'train_steps_per_second': 8.681, 'train_loss': 2.141612548828125, 'epoch': 5.0}
{'train_runtime': 5.5986, 'train_samples_per_second': 8.931, 'train_steps_per_second': 8.931, 'train_loss': 1.8536080932617187, 'epoch': 5.0}
{'train_runtime': 5.9531, 'train_samples_per_second': 8.399, 'train_steps_per_second': 8.399, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 6.2077, 'train_samples_per_second': 8.055, 'train_steps_per_second': 8.055, 'train_loss': 2.7567929077148436, 'epoch': 5.0}
{'train_runtime': 5.7711, 'train_samples_per_second': 8.664, 'train_steps_per_second': 8.664, 'train_loss': 2.7693902587890626, 'epoch': 5.0}
{'train_runtime': 5.5843, 'train_samples_per_second': 8.954, 'train_steps_per_second': 8.954, 'train_loss': 2.341680450439453, 'epoch': 5.0}
{'train_runtime': 5.6385, 'train_samples_per_second': 8.868, 'train_steps_per_second': 8.868, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 5.6692, 'train_samples_per_second': 8.82, 'train_steps_per_second': 8.82, 'train_loss': 2.7204470825195313, 'epoch': 5.0}
{'train_runtime': 5.6554, 'train_samples_per_second': 8.841, 'train_steps_per_second': 8.841, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 6.2536, 'train_samples_per_second': 7.995, 'train_steps_per_second': 7.995, 'train_loss': 2.73941650390625, 'epoch': 5.0}
{'train_runtime': 6.1263, 'train_samples_per_second': 8.161, 'train_steps_per_second': 8.161, 'train_loss': 2.328738098144531, 'epoch': 5.0}
{'train_runtime': 6.2334, 'train_samples_per_second': 8.021, 'train_steps_per_second': 8.021, 'train_loss': 2.672760009765625, 'epoch': 5.0}
{'train_runtime': 5.396, 'train_samples_per_second': 9.266, 'train_steps_per_second': 9.266, 'train_loss': 2.5048171997070314, 'epoch': 5.0}
{'train_runtime': 6.5121, 'train_samples_per_second': 7.678, 'train_steps_per_second': 7.678, 'train_loss': 2.6475540161132813, 'epoch': 5.0}
{'train_runtime': 6.242, 'train_samples_per_second': 8.01, 'train_steps_per_second': 8.01, 'train_loss': 2.4212435913085937, 'epoch': 5.0}
{'train_runtime': 6.2226, 'train_samples_per_second': 8.035, 'train_steps_per_second': 8.035, 'train_loss': 2.665640563964844, 'epoch': 5.0}
{'train_runtime': 6.1284, 'train_samples_per_second': 8.159, 'train_steps_per_second': 8.159, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 6.0692, 'train_samples_per_second': 8.238, 'train_steps_per_second': 8.238, 'train_loss': 2.677030334472656, 'epoch': 5.0}
{'train_runtime': 6.2254, 'train_samples_per_second': 8.032, 'train_steps_per_second': 8.032, 'train_loss': 2.5631097412109374, 'epoch': 5.0}
{'train_runtime': 6.1928, 'train_samples_per_second': 8.074, 'train_steps_per_second': 8.074, 'train_loss': 2.7035861206054688, 'epoch': 5.0}
{'train_runtime': 6.2952, 'train_samples_per_second': 7.943, 'train_steps_per_second': 7.943, 'train_loss': 2.1366070556640624, 'epoch': 5.0}
{'train_runtime': 6.6555, 'train_samples_per_second': 7.513, 'train_steps_per_second': 7.513, 'train_loss': 2.5963677978515625, 'epoch': 5.0}
{'train_runtime': 5.7046, 'train_samples_per_second': 8.765, 'train_steps_per_second': 8.765, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 6.2968, 'train_samples_per_second': 7.94, 'train_steps_per_second': 7.94, 'train_loss': 2.444275665283203, 'epoch': 5.0}
{'train_runtime': 6.0757, 'train_samples_per_second': 8.229, 'train_steps_per_second': 8.229, 'train_loss': 2.758072509765625, 'epoch': 5.0}

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

{'train_runtime': 5.5881, 'train_samples_per_second': 8.948, 'train_steps_per_second': 8.948, 'train_loss': 2.5308186340332033, 'epoch': 5.0}
{'train_runtime': 5.5116, 'train_samples_per_second': 9.072, 'train_steps_per_second': 9.072, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 6.1541, 'train_samples_per_second': 8.125, 'train_steps_per_second': 8.125, 'train_loss': 2.5968612670898437, 'epoch': 5.0}
{'train_runtime': 6.1464, 'train_samples_per_second': 8.135, 'train_steps_per_second': 8.135, 'train_loss': 2.3421511840820313, 'epoch': 5.0}
{'train_runtime': 6.2721, 'train_samples_per_second': 7.972, 'train_steps_per_second': 7.972, 'train_loss': 2.8151095581054686, 'epoch': 5.0}
{'train_runtime': 6.2383, 'train_samples_per_second': 8.015, 'train_steps_per_second': 8.015, 'train_loss': 2.5277490234375, 'epoch': 5.0}
{'train_runtime': 6.5339, 'train_samples_per_second': 7.652, 'train_steps_per_second': 7.652, 'train_loss': 2.6659759521484374, 'epoch': 5.0}
{'train_runtime': 5.8795, 'train_samples_per_second': 8.504, 'train_steps_per_second': 8.504, 'train_loss': 2.4205947875976563, 'epoch': 5.0}
{'train_runtime': 5.4937, 'train_samples_per_second': 9.101, 'train_steps_per_second': 9.101, 'train_loss': 2.9439349365234375, 'epoch': 5.0}
{'train_runtime': 5.6868, 'train_samples_per_second': 8.792, 'train_steps_per_second': 8.792, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 6.4137, 'train_samples_per_second': 7.796, 'train_steps_per_second': 7.796, 'train_loss': 2.7482623291015624, 'epoch': 5.0}
{'train_runtime': 6.2396, 'train_samples_per_second': 8.013, 'train_steps_per_second': 8.013, 'train_loss': 2.5622589111328127, 'epoch': 5.0}
{'train_runtime': 6.268, 'train_samples_per_second': 7.977, 'train_steps_per_second': 7.977, 'train_loss': 2.7974530029296876, 'epoch': 5.0}
{'train_runtime': 6.1058, 'train_samples_per_second': 8.189, 'train_steps_per_second': 8.189, 'train_loss': 2.145621032714844, 'epoch': 5.0}
{'train_runtime': 6.3311, 'train_samples_per_second': 7.898, 'train_steps_per_second': 7.898, 'train_loss': 2.863575744628906, 'epoch': 5.0}
{'train_runtime': 5.1028, 'train_samples_per_second': 9.799, 'train_steps_per_second': 9.799, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 6.2611, 'train_samples_per_second': 7.986, 'train_steps_per_second': 7.986, 'train_loss': 2.568789367675781, 'epoch': 5.0}
{'train_runtime': 6.2639, 'train_samples_per_second': 7.982, 'train_steps_per_second': 7.982, 'train_loss': 2.766044921875, 'epoch': 5.0}
{'train_runtime': 6.5833, 'train_samples_per_second': 7.595, 'train_steps_per_second': 7.595, 'train_loss': 2.561773376464844, 'epoch': 5.0}
{'train_runtime': 5.7938, 'train_samples_per_second': 8.63, 'train_steps_per_second': 8.63, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 6.1708, 'train_samples_per_second': 8.103, 'train_steps_per_second': 8.103, 'train_loss': 2.8372198486328126, 'epoch': 5.0}
{'train_runtime': 6.1819, 'train_samples_per_second': 8.088, 'train_steps_per_second': 8.088, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 6.3937, 'train_samples_per_second': 7.82, 'train_steps_per_second': 7.82, 'train_loss': 2.6863693237304687, 'epoch': 5.0}
{'train_runtime': 5.9037, 'train_samples_per_second': 8.469, 'train_steps_per_second': 8.469, 'train_loss': 2.3290318298339843, 'epoch': 5.0}
{'train_runtime': 6.403, 'train_samples_per_second': 7.809, 'train_steps_per_second': 7.809, 'train_loss': 2.8153952026367186, 'epoch': 5.0}
{'train_runtime': 6.107, 'train_samples_per_second': 8.187, 'train_steps_per_second': 8.187, 'train_loss': 2.520637664794922, 'epoch': 5.0}
{'train_runtime': 6.3897, 'train_samples_per_second': 7.825, 'train_steps_per_second': 7.825, 'train_loss': 2.6659759521484374, 'epoch': 5.0}
{'train_runtime': 6.1562, 'train_samples_per_second': 8.122, 'train_steps_per_second': 8.122, 'train_loss': 2.4155119323730467, 'epoch': 5.0}
{'train_runtime': 6.5307, 'train_samples_per_second': 7.656, 'train_steps_per_second': 7.656, 'train_loss': 2.795140380859375, 'epoch': 5.0}
{'train_runtime': 5.9902, 'train_samples_per_second': 8.347, 'train_steps_per_second': 8.347, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 6.5474, 'train_samples_per_second': 7.637, 'train_steps_per_second': 7.637, 'train_loss': 2.718914794921875, 'epoch': 5.0}
{'train_runtime': 5.821, 'train_samples_per_second': 8.59, 'train_steps_per_second': 8.59, 'train_loss': 2.57347900390625, 'epoch': 5.0}
{'train_runtime': 6.2059, 'train_samples_per_second': 8.057, 'train_steps_per_second': 8.057, 'train_loss': 2.7790716552734374, 'epoch': 5.0}
{'train_runtime': 6.0968, 'train_samples_per_second': 8.201, 'train_steps_per_second': 8.201, 'train_loss': 2.146808929443359, 'epoch': 5.0}
{'train_runtime': 6.5354, 'train_samples_per_second': 7.651, 'train_steps_per_second': 7.651, 'train_loss': 2.623035888671875, 'epoch': 5.0}
{'train_runtime': 5.8495, 'train_samples_per_second': 8.548, 'train_steps_per_second': 8.548, 'train_loss': 2.4554617309570315, 'epoch': 5.0}
{'train_runtime': 6.2471, 'train_samples_per_second': 8.004, 'train_steps_per_second': 8.004, 'train_loss': 2.6399609375, 'epoch': 5.0}
{'train_runtime': 6.1557, 'train_samples_per_second': 8.123, 'train_steps_per_second': 8.123, 'train_loss': 2.766897888183594, 'epoch': 5.0}
{'train_runtime': 6.1348, 'train_samples_per_second': 8.15, 'train_steps_per_second': 8.15, 'train_loss': 2.485086212158203, 'epoch': 5.0}
{'train_runtime': 6.1373, 'train_samples_per_second': 8.147, 'train_steps_per_second': 8.147, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 6.0635, 'train_samples_per_second': 8.246, 'train_steps_per_second': 8.246, 'train_loss': 2.669631042480469, 'epoch': 5.0}
{'train_runtime': 5.4587, 'train_samples_per_second': 9.16, 'train_steps_per_second': 9.16, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 5.7422, 'train_samples_per_second': 8.708, 'train_steps_per_second': 8.708, 'train_loss': 3.5120574951171877, 'epoch': 5.0}
{'train_runtime': 5.7201, 'train_samples_per_second': 8.741, 'train_steps_per_second': 8.741, 'train_loss': 2.340806884765625, 'epoch': 5.0}
{'train_runtime': 5.7478, 'train_samples_per_second': 8.699, 'train_steps_per_second': 8.699, 'train_loss': 3.472654113769531, 'epoch': 5.0}
{'train_runtime': 5.6559, 'train_samples_per_second': 8.84, 'train_steps_per_second': 8.84, 'train_loss': 2.5063441467285155, 'epoch': 5.0}
{'train_runtime': 5.7715, 'train_samples_per_second': 8.663, 'train_steps_per_second': 8.663, 'train_loss': 2.461853790283203, 'epoch': 5.0}
{'train_runtime': 5.6871, 'train_samples_per_second': 8.792, 'train_steps_per_second': 8.792, 'train_loss': 2.4235484313964846, 'epoch': 5.0}
{'train_runtime': 5.7168, 'train_samples_per_second': 8.746, 'train_steps_per_second': 8.746, 'train_loss': 2.710418701171875, 'epoch': 5.0}
{'train_runtime': 5.6853, 'train_samples_per_second': 8.795, 'train_steps_per_second': 8.795, 'train_loss': 2.7677490234375, 'epoch': 5.0}
{'train_runtime': 5.5895, 'train_samples_per_second': 8.945, 'train_steps_per_second': 8.945, 'train_loss': 3.2928485107421874, 'epoch': 5.0}
{'train_runtime': 5.536, 'train_samples_per_second': 9.032, 'train_steps_per_second': 9.032, 'train_loss': 2.5639434814453126, 'epoch': 5.0}
{'train_runtime': 5.5469, 'train_samples_per_second': 9.014, 'train_steps_per_second': 9.014, 'train_loss': 2.6188955688476563, 'epoch': 5.0}
{'train_runtime': 5.6958, 'train_samples_per_second': 8.778, 'train_steps_per_second': 8.778, 'train_loss': 2.146657257080078, 'epoch': 5.0}
{'train_runtime': 6.773, 'train_samples_per_second': 7.382, 'train_steps_per_second': 7.382, 'train_loss': 3.048661193847656, 'epoch': 5.0}
{'train_runtime': 5.7289, 'train_samples_per_second': 8.728, 'train_steps_per_second': 8.728, 'train_loss': 2.4536985778808593, 'epoch': 5.0}
{'train_runtime': 5.6994, 'train_samples_per_second': 8.773, 'train_steps_per_second': 8.773, 'train_loss': 3.03739501953125, 'epoch': 5.0}
{'train_runtime': 5.6221, 'train_samples_per_second': 8.893, 'train_steps_per_second': 8.893, 'train_loss': 2.7613510131835937, 'epoch': 5.0}

Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
GPU 0:  98%|█████████▊| 59/60 [14:11<00:14, 14.34s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1:  98%|█████████▊| 59/60 [14:14<00:14, 14.31s/it]Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.

GPU 1: 100%|██████████| 60/60 [14:28<00:00, 14.29s/it]

{'train_runtime': 5.7253, 'train_samples_per_second': 8.733, 'train_steps_per_second': 8.733, 'train_loss': 2.035836486816406, 'epoch': 5.0}
{'train_runtime': 5.6258, 'train_samples_per_second': 8.888, 'train_steps_per_second': 8.888, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 5.7831, 'train_samples_per_second': 8.646, 'train_steps_per_second': 8.646, 'train_loss': 2.5317152404785155, 'epoch': 5.0}
{'train_runtime': 5.6112, 'train_samples_per_second': 8.911, 'train_steps_per_second': 8.911, 'train_loss': 2.806283264160156, 'epoch': 5.0}
{'train_runtime': 6.2757, 'train_samples_per_second': 7.967, 'train_steps_per_second': 7.967, 'train_loss': 2.675413818359375, 'epoch': 5.0}
{'train_runtime': 6.2079, 'train_samples_per_second': 8.054, 'train_steps_per_second': 8.054, 'train_loss': 2.3514976501464844, 'epoch': 5.0}
{'train_runtime': 6.4646, 'train_samples_per_second': 7.734, 'train_steps_per_second': 7.734, 'train_loss': 2.6587396240234376, 'epoch': 5.0}
{'train_runtime': 5.6754, 'train_samples_per_second': 8.81, 'train_steps_per_second': 8.81, 'train_loss': 2.806283264160156, 'epoch': 5.0}

[INFO] All batches processed

In [44]:
results

[{'explanation_type': "<class 'explanations.TopKLeastInfluential'>",
  'estimator': 'DataInfEstimator:fast_implementation=True',
  't_stat': 0.8266051212848249,
  'p_val': 0.2149149383739613,
  'mean_diff': 0.9929018020629883},
 {'explanation_type': "<class 'explanations.TopKLeastInfluential'>",
  'estimator': 'LESSEstimator:normalize=False',
  't_stat': 2.311290985942926,
  'p_val': 0.023069453099132217,
  'mean_diff': 1.9455487966537475},
 {'explanation_type': "<class 'explanations.TopKLeastInfluential'>",
  'estimator': 'LESSEstimator:normalize=True',
  't_stat': 2.659904395866568,
  'p_val': 0.013024938475023406,
  'mean_diff': 2.081648755073547},
 {'explanation_type': "<class 'explanations.TopKLeastOrthogonal'>",
  'estimator': 'DataInfEstimator:fast_implementation=True',
  't_stat': 1.6205862766166925,
  'p_val': 0.06977879532349232,
  'mean_diff': 1.5247912168502809},
 {'explanation_type': "<class 'explanations.TopKLeastOrthogonal'>",
  'estimator': 'LESSEstimator:normalize=False',
  't_stat': 0.3571139873371315,
  'p_val': 0.3646183985179806,
  'mean_diff': 0.44708390235900886},
 {'explanation_type': "<class 'explanations.TopKLeastOrthogonal'>",
  'estimator': 'LESSEstimator:normalize=True',
  't_stat': -0.21747141472043563,
  'p_val': 0.5836543639189531,
  'mean_diff': -0.3801732897758483},
 {'explanation_type': "<class 'explanations.TopKMostInfluential'>",
  'estimator': 'DataInfEstimator:fast_implementation=True',
  't_stat': 1.5546481063242743,
  'p_val': 0.07722558735638917,
  'mean_diff': 1.470047378540039},
 {'explanation_type': "<class 'explanations.TopKMostInfluential'>",
  'estimator': 'LESSEstimator:normalize=False',
  't_stat': 0.619080333466728,
  'p_val': 0.2756050470397413,
  'mean_diff': 0.8010127305984496},
 {'explanation_type': "<class 'explanations.TopKMostInfluential'>",
  'estimator': 'LESSEstimator:normalize=True',
  't_stat': -0.17507043450969137,
  'p_val': 0.5675502094812742,
  'mean_diff': -0.30731376409530653},
 {'explanation_type': "<class 'explanations.TopKMostOrthogonal'>",
  'estimator': 'DataInfEstimator:fast_implementation=True',
  't_stat': 2.408122517359317,
  'p_val': 0.019685020650835484,
  'mean_diff': 2.0577053785324098},
 {'explanation_type': "<class 'explanations.TopKMostOrthogonal'>",
  'estimator': 'LESSEstimator:normalize=False',
  't_stat': 2.143305098220755,
  'p_val': 0.030347054037992722,
  'mean_diff': 1.6136228799819947},
 {'explanation_type': "<class 'explanations.TopKMostOrthogonal'>",
  'estimator': 'LESSEstimator:normalize=True',
  't_stat': 2.371569859447088,
  'p_val': 0.020900640012155764,
  'mean_diff': 1.9408782720565796}]

In [ ]:
import pandas as pd
df = pd.DataFrame([ x
    for xs in results
    for x in xs
],columns=["setting","estimator","explanation", "explanation_type", "test_instance_idx", "gain"])
df["test_instance_idx"] = df["test_instance_idx"].apply(lambda x: x[0][0])
df["explanation_type"] = df["explanation_type"].apply(str)

df.set_index(["setting", "estimator","explanation_type", "test_instance_idx"])

TypeError: 'float' object is not subscriptable

In [ ]:
# df = pd.concat([df,df,df])

In [ ]:
# group_random

In [37]:
import pandas as pd
from scipy.stats import ttest_rel

results = []

for (explanation_type, estimator), group in df.groupby(["explanation_type", "estimator"]):
    group_explanation = group[group["setting"] == "explanation"]["gain"]
    group_random = group[group["setting"] == "random"]["gain"]
    
    t_stat, p_val = ttest_rel(group_explanation, group_random, alternative="greater")
    mean_diff = group_explanation.mean() - group_random.mean()
    
    results.append({
        "explanation_type": explanation_type,
        "estimator": estimator,
        "t_stat": t_stat,
        "p_val": p_val,
        "mean_diff": mean_diff
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="p_val")

In [38]:
results_df[results_df["explanation_type"].str.contains("LeastIn")].sort_values(by="p_val")

,explanation_type,estimator,t_stat,p_val,mean_diff
2,<class 'explanations.TopKLeastInfluential'>,LESSEstimator:normalize=True,2.659904,0.013025,2.081649
1,<class 'explanations.TopKLeastInfluential'>,LESSEstimator:normalize=False,2.311291,0.023069,1.945549
0,<class 'explanations.TopKLeastInfluential'>,DataInfEstimator:fast_implementation=True,0.826605,0.214915,0.992902

In [39]:
results_df[results_df["explanation_type"].str.contains("MostIn")].sort_values(by="p_val")

,explanation_type,estimator,t_stat,p_val,mean_diff
6,<class 'explanations.TopKMostInfluential'>,DataInfEstimator:fast_implementation=True,1.554648,0.077226,1.470047
7,<class 'explanations.TopKMostInfluential'>,LESSEstimator:normalize=False,0.619080,0.275605,0.801013
8,<class 'explanations.TopKMostInfluential'>,LESSEstimator:normalize=True,-0.175070,0.567550,-0.307314

In [15]:
df.describe()

       test_instance_idx        gain
count         240.000000  240.000000
mean          649.400000   -0.297139
std           324.798396    2.375006
min           127.000000   -8.421473
25%           260.000000   -0.527687
50%           833.000000    0.509406
75%           916.000000    1.060665
max           978.000000    2.912562